name: 01 - Building Blocks
on:
  push:
  workflow_dispatch:
    
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"

  echo-together:
    runs-on: ubuntu-latest
    steps:
      - name: Success Step
        run: |
          echo "This step will succeed"
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye"
        