name: 03 Work Flow Runners
on: 
    workflow_dispatch:

jobs:
    unbuntu-runner:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "I am running on ${{ runner.os }}"
                echo "Runner OS: $RUNNER_OS"
    
    windows-runner:
        runs-on: windows-latest
        steps:
            - name: Show Windows OS
              run: |
                echo "I am running on ${{ runner.os }}"
                echo "Runner OS: $RUNNER_OS"